version: '3.7'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.dev
    environment:
      - PORT=${PORT}
    ports:
      - 3000:3000
